Repository pye-community/pye-community-bot, pull requests merged in 2023-10, with the labels that each got.

#16 Fix: Enviroment fixes for start.
  .eslintignore
  .gitignore
  LICENSE
  package.json
  pnpm-lock.yaml
  src/commands/ping.ts
  src/config.ts
  src/events/handlers/cohereAIHandler.ts
  src/events/handlers/nsfwFilter.ts
  src/events/interactionCreate.ts
  src/index.ts
  src/modules/bot/eventsLoader.ts
  src/modules/bot/slashCommandsLoader.ts
  tsconfig.json
Labels: bug

#21 Lint fixes
  package.json
  src/events/handlers/nsfwFilter.ts
Labels: bug

#18 Refactor(handler): Enhanced Command Handling, Basic Commands, and Modularized Client Class
  .eslintrc.json
  .prettierignore
  .prettierrc.js
  .prettierrc.json
  pnpm-lock.yaml
  src/commands/developer/eval.ts
  src/commands/ping.ts
  src/commands/utility/help.ts
  src/commands/utility/ping.ts
  src/config.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/ready.ts
  src/events/threadCreate.ts
  src/index.ts
  src/modules/bot/eventsLoader.ts
  src/modules/bot/functions/nsfwFilter.ts
  src/modules/bot/functions/threadsAi.ts
  src/modules/bot/handlers.ts
  src/modules/bot/slashCommandsLoader.ts
Labels: enhancement

#25 feat|refactor: using hugging face inference with nsfw filter model
  .gitignore
  package.json
  src/config.ts
  src/modules/bot/functions/nsfwFilter.ts
  src/modules/helpers/reporting.ts
Labels: enhancement

#34 Fix/slash commands register
  src/index.ts
Labels: bug

#31 chore/remove unnecesary dependencies
  package.json
  pnpm-lock.yaml
Labels: enhancement

#27 fix/improved README and minor Fixes to NSFW Filter
  README.md
  src/modules/bot/functions/nsfwFilter.ts
  src/modules/helpers/reporting.ts
Labels: enhancement

#29 chore/remove prettier
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#32 feat/error logger implementation
  src/commands/developer/eval.ts
  src/config.ts
  src/events/interactionCreate.ts
  src/index.ts
  src/modules/bot/handlers.ts
  src/modules/helpers/reporting.ts
Labels: enhancement

#38 Feature/share threads
  src/commands/utility/help.ts
  src/config.ts
  src/events/threadCreate.ts
  src/modules/bot/functions/shareThread.ts
  src/utils/text.ts
Labels: enhancement

#44 refactor: report error and remove not thread channels config list
  src/config.ts
  src/events/interactionCreate.ts
  src/events/threadCreate.ts
  src/index.ts
  src/modules/bot/functions/nsfwFilter.ts
  src/modules/helpers/reporting.ts
Labels: enhancement

#47 fix/resolve Cohere Error When Uploading Unknown Files
  src/config.ts
  src/modules/bot/functions/threadsAi.ts
Labels: bug

#48 Refactor/embed error object
  src/modules/helpers/reporting.ts
Labels: enhancement

#49 Refactor/flat folders structure
  src/commands/developer/eval.ts
  src/commands/utility/help.ts
  src/commands/utility/ping.ts
  src/events/interactionCreate.ts
  src/events/messageCreate.ts
  src/events/threadCreate.ts
  src/functions/nsfwFilter.ts
  src/functions/shareThread.ts
  src/functions/threadsAi.ts
  src/handlers.ts
  src/helpers/reporting.ts
  src/index.ts
Labels: documentation, enhancement
